/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcmasterbaja_binary_csv_BinaryToCSV */

#ifndef _Included_com_mcmasterbaja_binary_csv_BinaryToCSV
#define _Included_com_mcmasterbaja_binary_csv_BinaryToCSV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcmasterbaja_binary_csv_BinaryToCSV
 * Method:    toCSV
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_mcmasterbaja_binary_1csv_BinaryToCSV_toCSV
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     com_mcmasterbaja_binary_csv_BinaryToCSV
 * Method:    bytesToCSV
 * Signature: ([BLjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_mcmasterbaja_binary_1csv_BinaryToCSV_bytesToCSV
  (JNIEnv *, jclass, jbyteArray, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
