/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backend_API_storage_BinaryTOCSV */

#ifndef _Included_backend_API_storage_BinaryTOCSV
#define _Included_backend_API_storage_BinaryTOCSV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backend_API_storage_BinaryTOCSV
 * Method:    toCSV
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_backend_API_storage_BinaryTOCSV_toCSV
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
