/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backend_API_binary_csv_BinaryTOCSV */

#ifndef _Included_backend_API_binary_csv_BinaryTOCSV
#define _Included_backend_API_binary_csv_BinaryTOCSV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backend_API_binary_csv_BinaryTOCSV
 * Method:    toCSV
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_backend_API_binary_1csv_BinaryTOCSV_toCSV
  (JNIEnv *, jclass, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
