# This is a basic workflow to help you get started with Actions
name: Lint Demo
run-name: Testing 

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build with Maven"

    steps:
    - run: echo "${{ toJson(github) }}"

    - run: echo ${GITHUB_REF##*/}

    - run: echo ${ toJson(GITHUB_REF) }
    
