# This is a basic workflow to help you get started with Actions
name: Lint Demo
run-name: Testing ${{ github.head_ref}} ${{ github.event.pull_request.title }}

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build with Maven"

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: cd ./API && mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn package --file pom.xml
