# This is a basic workflow to help you get started with Actions
name: Linting, Building and Testing
run-name: Testing | ${{ github.head_ref}} | ${{ github.event.pull_request.title }}

on: [pull_request]

jobs:
  Build_Java_With_Maven:
    runs-on: ubuntu-latest
    name: "Build Backend with Java and Maven"

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--replace"
        skip-commit: true
    
    - name: Print diffs
      run: git --no-pager diff --exit-code

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: cd ./backend && mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn package --file pom.xml

    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-app
        path: ./backend/target

  Build_Node_js:
    runs-on: ubuntu-latest
    name: "Build Frontend with Node.js"

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: front-end/package-lock.json

    - name: Install dependencies
      run: npm ci --force
      working-directory: ./front-end

    - name: Build
      run: npm run build --if-present
      working-directory: ./front-end

    # - name: Test
    #   run: npm test
    #   working-directory: ./front-end

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: ./front-end/build


  Playwright_Tests:
    runs-on: ubuntu-latest
    needs: [Build_Java_With_Maven, Build_Node_js]
    name: "Run Playwright Tests"

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Download backend artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-app
        path: ./backend/target

    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: ./front-end/build

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install dependencies for Playwright
      run: npm ci
      working-directory: ./e2e

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start Backend Server
      run: java -jar -Dquarkus.http.host=localhost ./backend/target/quarkus-app/quarkus-run.jar &

    - name: Serve the project
      working-directory: front-end
      run: |
        npm install -g serve
        serve -s build -l 5173 &
      continue-on-error: true

    # - name: Install Xvfb
    #   run: sudo apt-get install -y xvfb

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libcups2 libdrm2
    

    # - name: Run Playwright tests with Xvfb
    #   env:
    #     DEBUG: pw:browser*,pw:api
    #   run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npx playwright test
    #   working-directory: ./e2e

    - name: Run Playwright tests
      env:
        DEBUG: pw:browser*,pw:api
        MOZ_HEADLESS: 1
        GTK_PATH: /usr/lib/x86_64-linux-gnu/gtk-3.0
      run: npx playwright test
      working-directory: ./e2e

    - name: Upload Playwright report
      if: failure() || always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: ./e2e/playwright-report/
        retention-days: 30