# This is a basic workflow to help you get started with Actions
name: Linting, Building and Testing
run-name: Testing | ${{ github.head_ref}} | ${{ github.event.pull_request.title }}

on: [pull_request]

jobs:
  Build_Java_With_Maven:
    runs-on: ubuntu-latest
    name: "Build Backend with Java and Maven"

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--replace"
        skip-commit: true
    
    - name: Print diffs
      run: git --no-pager diff --exit-code

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: cd ./backend && mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn package --file pom.xml

  Build_Node_js:
    runs-on: ubuntu-latest
    name: "Build Frontend with Node.js"

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front-end/package-lock.json

    - name: Install dependencies
      run: npm ci --force
      working-directory: ./front-end

    - name: Build
      run: npm run build --if-present
      working-directory: ./front-end

    # - name: Test
    #   run: npm test
    #   working-directory: ./front-end
